export const productos = [
  {
    codigo: 1001,
    nombre: "Bourbon Clásico",
    descripcion: "Café suave y balanceado con notas dulces de caramelo y frutas rojas. Ideal para quienes buscan una taza clásica y aromática.",
    presentacion: "1 kg",
    precio: 55000,
    categoria: "cafe",
    productor: "Finca El Mirador - Familia Ramírez",
    img: "../public/productos/cafe-bourbon.webp",
    alt: "Café variedad Bourbon",
    cantidad_inventario: 100,
    cantidad_carrito: 0
  },
  {
    codigo: 1002,
    nombre: "Catuai Dorado",
    descripcion: "Café de cuerpo medio y acidez brillante, con sabores que recuerdan a cítricos y chocolate. Perfecto para métodos filtrados.",
    presentacion: "1 kg",
    precio: 52000,
    categoria: "cafe",
    productor: "Finca la Arboleda - Don Julián y su familia",
    img: "../public/productos/cafe-catui.webp",
    alt: "Cafe variedad catui",
    cantidad_inventario: 100,
    cantidad_carrito: 0
  },
  {
    codigo: 1003,
    nombre: "Herencia Etíope Floral",
    descripcion: "Café exótico de perfil floral e intenso aroma, con notas a jazmín, frutos tropicales y un retrogusto prolongado. Una experiencia de origen ancestral.",
    presentacion: "1 kg",
    precio: 60000,
    categoria: "cafe",
    productor: "Finca Los Andes - Cooperativa Mujeres Cafeteras",
    img: "../public/productos/etiope.webp",
    alt: "Cafe variedad herencia etiope",
    cantidad_inventario: 100,
    cantidad_carrito: 0
  },
  {
    codigo: 1004,
    nombre: "Gesha Premium",
    descripcion: "Café exclusivo y reconocido mundialmente por su delicadeza. Notas florales, miel y frutas tropicales que lo convierten en una joya gourmet.",
    presentacion: "250 g",
    precio: 48000,
    categoria: "cafe",
    productor: "Finca Santa Rosa – Familia Gutiérrez",
    img: "../public/productos/gesha.webp",
    alt: "Cafe variedad Gesha",
    cantidad_inventario: 100,
    cantidad_carrito: 0
  },
  {
    codigo: 1005,
    nombre: "Aroma de Paz",
    descripcion: "Chocolate artesanal elaborado con cacao fino de aroma, símbolo de resiliencia y esperanza. Cada barra cuenta una historia de transformación.",
    presentacion: "500 g",
    precio: 10500,
    categoria: "cacao",
    productor: "Mujeres víctimas del conflicto en Rionegro, Santander",
    img: "../public/productos/cacao-paz.webp",
    alt: "Chocolate aroma de paz",
    cantidad_inventario: 100,
    cantidad_carrito: 0
  },
  {
    codigo: 1006,
    nombre: "Anori",
    descripcion: "Surge como un producto de sustitución voluntaria de cultivos ilícitos en Anorí, Antioquia, con altos estándares de calidad y sostenibilidad.",
    presentacion: "500 g",
    precio: 12000,
    categoria: "cacao",
    productor: "ASOMUCAN",
    img: "../public/productos/Anori.png",
    alt: "Anori",
    cantidad_inventario: 100,
    cantidad_carrito: 0
  },
  {
    codigo: 1007,
    nombre: "La Roja",
    descripcion: "Producida por excombatientes de las FARC-EP en Bogotá. Busca generar ingresos para los excombatientes y sus familias, así como promover la reconciliación.",
    presentacion: "330 ml",
    precio: 7500,
    categoria: "cerveza",
    productor: "Ex-combatientes de las FARC",
    img: "../public/productos/laroja.png",
    alt: "La Roja",
    cantidad_inventario: 100,
    cantidad_carrito: 0
  },
  {
    codigo: 1008,
    nombre: "La Trocha",
    descripcion: "Producida por excombatientes de las FARC-EP en Bogotá. Busca generar ingresos para los excombatientes y sus familias, así como promover la reconciliación.",
    presentacion: "330 ml",
    precio: 6000,
    categoria: "cerveza",
    productor: "Ex-combatientes de las FARC",
    img: "../public/productos/latrocha.png",
    alt: "La Trocha",
    cantidad_inventario: 100,
    cantidad_carrito: 0
  },
  {
    codigo: 1009,
    nombre: "Cordillera",
    descripcion: "Una marca de chocolate sostenible que apoya proyectos productivos de cacao en zonas de reincorporación, buscando fortalecer el desarrollo económico y social.",
    presentacion: "500 gr",
    precio: 15000,
    categoria: "cacao",
    productor: "Cordillera Company",
    img: "../public/productos/Cordillera.png",
    alt: "Cordillera",
    cantidad_inventario: 100,
    cantidad_carrito: 0
  },
  {
    codigo: 1010,
    nombre: "Late Choco",
    descripcion: "Una fábrica artesanal que utiliza cacao cultivado por familias víctimas del conflicto armado en el Chocó.",
    presentacion: "500 gr",
    precio: 14000,
    categoria: "cacao",
    productor: "Late Chocó",
    img: "../public/productos/latechoco.png",
    alt: "Late Choco",
    cantidad_inventario: 100,
    cantidad_carrito: 0
  }
];
